import React from "react";
import { Inter } from "next/font/google";
import { ConfigProvider, Layout, theme } from "antd";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import "./globals.css";
import AppHeader from "./components/AppHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <ConfigProvider
          theme={{
            token: {
              colorText: "white",
            },
          }}
        >
          <AppHeader />
          {children}
        </ConfigProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
